#!/bin/sh

uci -q get ttyd || exit 0

uci -q batch <<-EOF >/dev/null
	set ttyd.@ttyd[0].interface='127.0.0.1'
	commit ttyd
EOF

cat <<-EOF > /etc/nginx/conf.d/ttyd.locations
location ~ ^/ttyd(.*)\$ {
	proxy_http_version 1.1;
	proxy_set_header Upgrade \$http_upgrade;
	proxy_set_header Connection "upgrade";
	proxy_pass http://127.0.0.1:7681/\$1;
}
EOF

sed -Ei "s/hostname\s*\+\s*':'\s*\+\s*port/host + '\/ttyd\/'/g" /www/luci-static/resources/view/ttyd/term.js

exit 0
