#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1
PROG="/usr/bin/iperf3"
NAME="iperf3-server"

_info() {
	logger -p daemon.info -t "$NAME" "$*"
}

_err() {
	logger -p daemon.err -t "$NAME" "$*"
}

main() {
	config_get main_enable $1 "main_enable"
}

start_instance() {
	local cfg="$1"
	local enable_server port delay extra_options
	for option in enable_server port delay extra_options
	do
		config_get $option $cfg "$option"
	done
	[ "$enable_server" = "1" -a "$port" -gt 0 ] && {
		_info "Starting iPerf3 Server with Port [$port] ..."
		echo "$(date) $(which iperf3) -s -D -p $port $extra_options" >> /tmp/iperf.log.txt
		ARGS="-s -D -p $port $extra_options"
    PRE_RUN=$(["$delay" -gt 0] && echo "sleep $delay &&")
		procd_open_instance
		procd_set_param command $PRE_RUN $PROG $ARGS
		procd_set_param stderr 1
		procd_close_instance
	}
}

start_service() {
  stop_service
	config_load "$NAME"
  config_foreach main "iperf3-server"
  [ "$main_enable" = "1" ] || return 0
	config_foreach start_instance "servers"
}

stop_service() {
	_info "Stop iperf3 server..."
  ps | grep "iperf3 -s -D" | awk '{print $1}' | while read PID; do kill -9 $PID; done
}

service_triggers() {
	procd_add_reload_trigger "$NAME"
}

reload_service() {
	stop
	start
}
